# Generated by Django 4.2.8 on 2024-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_timestamp_alter_student_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="publish",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="student",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
