# Generated by Django 4.2.8 on 2024-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
